# SURDEX Supersession
# Notes #
    # Currently, this script requests the shoreline-to-eez file input, but in the future, the shoreline-to-eez script be embedded and the final output called for the surdex supersession.
    # This script requires the SURDEX Supersession file generated by the Geospatial Applications Development Branch
    # Unsurveyed areas are replaced with a survey year equal to the minimum survey year within the SURDEX Supersession file. It is assumed that the fieldname for survey year within the SURDEX Supersession file contains "end"

# This script completes the following:
    # Reprojects the input SURDEX Superseded layer WGS84 EASE
    # Dissolves the input SURDEX Superseded layer by survey  year
    # Extends the SURDEX Superseded layer to the EEZ and replaces all non-surveyed areas with survey year equal to the minimum survey year within the SURDEX Supersession file. 

# Final Output is sdx_null_final named SURDEX_Superseded_Raster in the specified output geodatabase

import arcpy, os, csv, datetime  
from arcpy import env
from datetime import date

sl_eez = arcpy.GetParameter(0)
#sl_eez = r"C:\Users\Christina.Fandel\Documents\Fandel\NHSP\Data_Processing\Shoreline_to_EEZ\Shoreline_to_EEZ.gdb\USA_Shoreline_to_EEZ"
sdx = arcpy.GetParameter(1)
#sdx = r"C:\Users\Christina.Fandel\Documents\Fandel\NHSP\Data_Processing\SURDEX\Superseded_SURDEX.gdb\SURDEX_Superseded_TESTING"
output_ws = str(arcpy.GetParameter(2))
#output_ws = r"C:\Users\Christina.Fandel\Documents\Fandel\NHSP\Data_Processing\SURDEX\Superseded_SURDEX.gdb"
sdx_prj = os.path.join(output_ws, 'SURDEX_Superseded_WGS84EASE')
sdx_dissolve = os.path.join(output_ws, 'SURDEX_Superseded_DISSOLVE_ALL')
null = os.path.join(output_ws, 'USA_Shoreline_to_EEZ_Minus_SURDEX') 
min_year = date.today().year
sdx_null_m = os.path.join(output_ws, 'SURDEX_NULL_JOIN_temp')
sdx_null_m_d = os.path.join(output_ws, 'SURDEX_NULL_JOIN_temp2')
sdx_null = os.path.join(output_ws, 'SURDEX_NULL_Superseded')
sdx_null_final = os.path.join(output_ws, 'SURDEX_NULL_Superseded_Raster')
r_cell_size = arcpy.GetParameter(3)
#r_cell_size = 500

# Project SURDEX data to WGS84 EASE
arcpy.Project_management('%s'%(sdx), '%s'%(sdx_prj), arcpy.SpatialReference(3975))

# Extend existing SURDEX coverage to model bounds (shoreline-to-eez layer)
# 1. Generate null layer that includes all unsurveyed areas out to the EEZ and Repair Geometry (eliminate self-intersections). Clip dissolved SURDEX layer to model bounds. 
d_field = "dissolveNum"
arcpy.AddField_management(sdx_prj, d_field, "double")
arcpy.CalculateField_management(sdx_prj, d_field, 1)
arcpy.RepairGeometry_management('%s'%(sdx_prj))
arcpy.Dissolve_management(sdx_prj, sdx_dissolve, d_field)
arcpy.Erase_analysis(sl_eez, sdx_dissolve, null)

# 2. Identify fieldname for "survey year" and minimum survey year within SURDEX layer. Add "survey year" field to NULLL layer and denote "survey year" within NULL layer as minimum survey year within SURDEX. Assumes SURDEX fieldname has "year" within title. 
fields = arcpy.ListFields(sdx_prj)
for field in fields:
    if ("end" in field.name):
        y_field = str(field.name)
        rows = arcpy.SearchCursor(sdx_prj, "", "", y_field, "")
        for row in rows:
            if row.getValue(y_field) < min_year:
                min_year = row.getValue(y_field)

arcpy.AddField_management(null, y_field, "double")
arcpy.CalculateField_management(null, y_field, min_year)

# 3.  Merge non-surveyed areas denoted with minimum with original SURDEX layer, Dissolve by Surdex year, and Clip output to model bounds
arcpy.Merge_management([sdx_prj, null], sdx_null_m)
arcpy.Dissolve_management(sdx_null_m, sdx_null_m_d, y_field)
arcpy.Clip_analysis(sdx_null_m_d, sl_eez, sdx_null)

# Generate raster of final superseded SURDEX layer
arcpy.PolygonToRaster_conversion(sdx_null, y_field, sdx_null_final, "MAXIMUM_COMBINED_AREA", y_field, r_cell_size)                

# Delete temporary files
tempfiles = [sdx_prj, sdx_dissolve, null, sdx_null_m, sdx_null_m_d, sdx_null]
for tempfile in tempfiles:
    arcpy.Delete_management('%s'%(tempfile))