BLUETOPO:
  SUBFOLDER: model_variables/Prediction/pre_processed
DIGITALCOAST:
  SUBFOLDER: model_variables/Prediction/raw
  API: https://coast.noaa.gov/dataviewer/api/v1/search/missions
  BUCKET: noaa-nos-coastal-lidar-pds
  TILED_SUBFOLDER: model_variables/Prediction/pre_processed/tiled
HURRICANE:
  COUNT_RASTER_PATH: original_data_files/hurricane_data/hurricane_count_raster
  CUMULATIVE_RASTER_PATH: original_data_files/hurricane_data/hurricane_cumulative_raster
  DATA_PATH: original_data_files/hurricane_data
  GPKG_PATH: original_data_files/hurricane_data/hurricane_data.gpkg
  RASTER_PATH: original_data_files/hurricane_data/hurricane_rasters
  YEAR_PAIR_RASTER_PATH: ER_3/model_variables/Prediction/pre_processed/hurricane_year_pair_rasters
LIDAR_PLOTS:
  INPUT_VRTS: pilot/model_variables/Prediction/raw/DigitalCoast
  PLOT_OUTPUTS: pilot/model_variables/Prediction/raw/DigitalCoast_plots
  RESAMPLED_VRTS: pilot/model_variables/Prediction/raw/DigitalCoast_resampled
MASK:
  SUBFOLDER: masks 
  COAST_BOUNDARY_PATH: coastal_boundary_dataset/50m_isobath_polygon/50m_isobath_polygon.shp
  MASKS_DIR: pilot/masks
  MASK_PRED_PATH: pilot/masks/prediction_mask_pilot.tif
  MASK_TRAINING_PATH: pilot/masks/training_mask_pilot.tif
  PREDICTION_MASK_PQ: pilot/masks/prediction_mask_pilot.parquet
  TRAINING_MASK_PQ: pilot/masks/training_mask_pilot.parquet
MODEL:
  MODEL_SUBGRIDS: pilot/model_subgrids
  PREPROCESSED_DIR: ER_3/model_variables/Prediction/pre_processed
  PREDICTION_OUTPUT_DIR: pilot/model_variables/Prediction/processed
  PREDICTION_TILES_DIR: pilot/model_variables/Prediction/prediction_tiles
  TRAINING_TILES_DIR: pilot/model_variables/Training/training_tiles
  SUBGRIDS: pilot/model_subgrids/Prediction.subgrid.WGS84_8m.gpkg
  PREDICTION_SUB_GRIDS: pilot/model_subgrids/prediction_intersecting_subgrids.gpkg
  TRAINING_SUB_GRIDS: pilot/model_subgrids/training_intersecting_subgrids.gpkg
  TRAINING_OUTPUT_DIR: pilot/model_variables/Training/processed
  UNCOMBINED_LIDAR_DIR: pilot/model_variables/Prediction/pre_processed/tiled_not_filled
PREPROCESSED:
  BLUETOPO: ER_3/model_variables/Prediction/pre_processed/BlueTopo
  HURRICANE: ER_3/model_variables/Prediction/pre_processed/hurricane_year_pair_rasters
  LIDAR: ER_3/model_variables/Prediction/pre_processed/tiled
  SEDIMENT: ER_3/model_variables/Prediction/pre_processed/sediment_rasters
  TSM: ER_3/original_data_files/tsm_data/TSM_year_pair_rasters/
S3:
  BUCKET_NAME: ocs-dev-csdl-hydrohealth
SEDIMENT:
  DATA_URL: https://cmgds.marine.usgs.gov/data/whcmsc/data-release/doi-P9H3LGWM/unpacked/usSEABED_EEZ/US9_ONE.csv
  DATA_PATH: original_data_files/sediment_data 
  GPKG_PATH: original_data_files/sediment_data/sediment_data.gpkg
  MASK_PATH: pilot/prediction_masks/prediction.mask.UTM17_8m.tif
  RASTER_PATH: ER_3/model_variables/Prediction/pre_processed/sediment_rasters
SHARED:
  BBOX_SHP: north_america_clip_wgs84.shp
  MASTER_GRIDS: Master_Grids.gpkg
  TILES: BlueTopo_Tile_Scheme_20250220_115927
  STATES: USA_Census_States_200km_Overlap
  ECOREGIONS: EcoRegions_50m
  ECOGRIDTILES: Eco_Region_Grid_Tiles
  MODELSUBGRIDTILES: Model_sub_Grid_Tiles
  BOUNDARY: USMaritimeLimitsNBoundaries_cz_1_100km
  OUTPUT_FOLDER: N:\CSDL\Projects\Hydro_Health_Model\HHM2025\working\HHM_Run
  OUTPUT_BUCKET: ocs-dev-csdl-hydrohealth
TERRAIN:
  COMBINED_LIDAR_DIR: pilot/model_variables/Prediction/processed/terrain_digitalcoast_outputs/combined_lidar_tifs
  INPUT_DIR: pilot/model_variables/Prediction/processed/terrain_digitalcoast_outputs
  FILLED_DIR: pilot/model_variables/Prediction/processed/terrain_digitalcoast_outputs/filled_tifs
  OUTPUTS: pilot/model_variables/Prediction/processed/terrain_digitalcoast_outputs
TSM:
  DATA_PATH: original_data_files/tsm_data/nc_files
  MEAN_RASTER_PATH: original_data_files/tsm_data/tsm_rasters/mean_rasters
  YEAR_PAIR_RASTER_PATH: ER_3/model_variables/Prediction/pre_processed/TSM_year_pair_rasters
