ACTIVECAPTAIN:
  API: https://marine.garmin.com/thirdparty-stage/api/v2/points-of-interest/bbox
  JSON: active_captain_points.json
DIGITALCOAST:
  API: https://maps.coast.noaa.gov/arcgis/rest/services/DAV/ElevationFootprints/MapServer/0/query?returnGeometry=false&f=json&where=1%3D1&outfields=%2A&spatialRel=esriSpatialRelIntersects&geometry=
  TILED_DATA: r'N:\HSD\Projects\HSD_DATA\NHSP_2_0\HH_2024\working\HHM_Run\ER_3\model_variables\Prediction\raw\ER_3\DigitalCoast\tiled'
GROUNDINGS:
  INCIDENTS: https://incidentnews.noaa.gov/raw/incidents.csv
  SERVICE: https://services8.arcgis.com/6ldl6K67FkYzPtEE/ArcGIS/rest/services/Significant_Maritime_Incidents__REG_Parameters__WFL1/FeatureServer/0/query?where=Incident_Type='GROUNDING'&outFields=*&units=esriSRUnit_Meter&returnGeometry=true&featureEncoding=esriDefault&returnQueryGeometry=true&returnExceededLimitFeatures=true&orderByFields='Year'&f=pgeojson
REEF:
  5KM: https://coralreefwatch.noaa.gov/product/vs/vs_polygons.json 
  1KM: https://datadownload-production.s3.us-east-1.amazonaws.com/WCMC008_CoralReefs2021_v4_1.zip
  ARTIFICIAL: https://marinecadastre.gov/downloads/data/mc/ArtificialReef.zip
  POLYGONS_1KM: global_reefs_1km\14_001_WCMC008_CoralReefs2021_v4_1\01_Data\WCMC008_CoralReef2021_Py_v4_1.shp
  POLYGONS_5KM: global_reef_polygons_5k.shp
  BUFFER_DISTANCE: 
    - 1852
    - 3704
  TANKER_BUFFER_DISTANCE:
    - 4360
    - 9260
    - 18520
    - 37040
TSM:
  DATA_PATH: r'N:\HSD\Projects\HSD_DATA\NHSP_2_0\HH_2024\working\HHM_Run\ER_3\original_data_files\tsm_data\nc_files'
  MEAN_RASTER_PATH: r"N:\HSD\Projects\HSD_DATA\NHSP_2_0\HH_2024\working\HHM_Run\ER_3\original_data_files\tsm_data\tsm_rasters\mean_rasters"
  YEAR_PAIR_RASTER_PATH: r"N:\HSD\Projects\HSD_DATA\NHSP_2_0\HH_2024\working\HHM_Run\ER_3\original_data_files\tsm_data\tsm_rasters\year_averages"

SEDIMENT:
  DATA_URL: r'https://cmgds.marine.usgs.gov/data/whcmsc/data-release/doi-P9H3LGWM/unpacked/usSEABED_EEZ/US9_ONE.csv'
  DATA_PATH: r"N:\HSD\Projects\HSD_DATA\NHSP_2_0\HH_2024\working\HHM_Run\ER_3\original_data_files\sediment_data"
  GPKG_PATH: r"N:\HSD\Projects\HSD_DATA\NHSP_2_0\HH_2024\working\HHM_Run\ER_3\original_data_files\sediment_data\sediment_data.gpkg"
  MASK_PATH: r"N:\HSD\Projects\HSD_DATA\NHSP_2_0\HH_2024\working\HHM_Run\ER_3\prediction_masks\prediction.mask.UTM17_8m.tif"
  RASTER_PATH: r"N:\HSD\Projects\HSD_DATA\NHSP_2_0\HH_2024\working\HHM_Run\ER_3\model_variables\Prediction\pre_processed\sediment_rasters"
SHARED:
  BBOX_SHP: north_america_clip_wgs84.shp
  MASTER_GRIDS: Master_Grids.gpkg
  TILES: BlueTopo_Tile_Scheme_20250220_115927
  STATES: USA_Census_States_200km_Overlap
  ECOREGIONS: EcoRegions_50m
  ECOGRIDTILES: Eco_Region_Grid_Tiles
  MODELSUBGRIDTILES: Model_sub_Grid_Tiles
  BOUNDARY: USMaritimeLimitsNBoundaries_cz_1_100km