EcoRegion-3:
  mosaic_NCMP_6344_1885_DEM_USGS_67613_resampled:
    use: false
    date: 1885
    year: 
    manual: 
    note: Thin vertical slice of data, don't use
  mosaic_NCMP_6346_1998_Lidar_USGS_48152_resampled:
    use: true
    date: 
    year: 1998
    manual: True
    note: Valid dataset    
  mosaic_NCMP_2779_2001_Lidar_USGS_50098_resampled:
    use: true
    date: 
    year: 
    manual: True
    note: Valid dataset 
  mosaic_NCMP_3746_2004_Lidar_USGS_50100_resampled:
    use: false
    date: 
    year: 
    manual: True
    note: Smaller mostly land dataset it looks like
  mosaic_NCMP_3747_2004_Lidar_USACE_50050_resampled:
    use: false
    date: 
    year: 
    manual: True
    note: Duplicate dataset like mosaic_NCMP_3747_2004_Lidar_USACE_50049_resampled, but smaller coverage area
  mosaic_NCMP_3747_2004_Lidar_USACE_50049_resampled:
    use: true
    date: 
    year: 
    manual: True
    note: Valid dataset, larger coverage than mosaic_NCMP_3747_2004_Lidar_USACE_50050_resampled
  mosaic_NCMP_3747_2006_Lidar_USACE_50059_resampled:
    use: true
    date: 
    year: 
    manual: True
    note: Valid dataset
  USACE_FL_State_Agencies_2007_529:
    use: true
    date: 2007-06-18, 2007-08-30
    year: null
    manual: false
    note: Valid dataset, however no 2007 datasets in the most recent download
  5498_USACE_USACE_NCMP_2009_8776:
    use: true
    date: 
    year: null
    manual: false
    note: Valid dataset, however no 2009 datasets in the most recent download
  mosaic_NCMP_4269_2010_DEM_USACE_NCMP_66659_resampled:
    use: true
    date: 
    year: 
    manual: 
    note: Valid dataset
  mosaic_NCMP_4269_2010_DEM_USACE_NCMP_66680_resampled:
    use: true
    date: 
    year: 
    manual: 
    note: Valid dataset 
  mosaic_NCMP_2883_2015_DEM_SRWMD_USGS_62877_resampled:
    use: false
    date: 
    year: 
    manual: 
    note: Don't use, small inland dataset
  mosaic_NCMP_1116_2015_DEM_USACE_USACE_NCMP_49581_resampled:
    use: true
    date: 
    year: 
    manual: 
    note: Valid dataset
  mosaic_NCMP_1116_2016_DEM_USACE_USACE_NCMP_49427_resampled:
    use: true
    date: 
    year: 
    manual: 
    note: Valid dataset
  mosaic_NCMP_2238_2017_DEM_SRWMD_USGS_62980_resampled:
    use: false
    date: 
    year: 
    manual: 
    note: Don't use, small inland dataset
  mosaic_NCMP_6318_2017_DEM_USACE_49424_resampled:
    use: true
    date: 
    year: 
    manual: 
    note: Valid dataset
  mosaic_NCMP_6318_2018_DEM_USACE_54685_resampled:
    use: true
    date: 
    year: 
    manual: 
    note: Valid dataset
  mosaic_NCMP_6350_2018_DEM_USDA_NRCS_USGS_59010_resampled:
    use: true
    date: 
    year: 
    manual: 
    note: Valid dataset
  mosaic_NCMP_6345_2020_DEM_USACE_NCMP_64385_resampled:
    use: true
    date: 
    year: 
    manual: 
    note: Valid dataset
  mosaic_NCMP_6346_2022_DEM_USACE_71740_resampled:
    use: false
    date: 
    year: 
    manual: 
    note: Don't use, duplicate dataset like mosaic_NCMP_6346_2022_DEM_USACE_NCMP_71772_resampled
  mosaic_NCMP_6345_2022_DEM_USACE_NCMP_75692_resampled:
    use: True
    date: 
    year: 
    manual: 
    note: Valid dataset that is not a duplicate
  mosaic_NCMP_6346_2022_DEM_USACE_NCMP_71772_resampled:
    use: true
    date: 
    year: 
    manual: 
    note: Valid dataset, duplicate dataset like mosaic_NCMP_6346_2022_DEM_USACE_71740_resampled 
  mosaic_NCMP_6346_2024_DEM_USACE_NCMP_73835_resampled:
    use: true
    date: 2024
    year: 
    manual: 
    note: Valid dataset