[Input]
root = ${Drives:HSD_DATA}
grid_dir = ${root}GRID\
grid_ws = ${grid_dir}Grid.gdb
US_shoreline = USA_Shoreline_NAEAC_Explode_Gen100m_Buffer707m
cell_size_comment = NOTE: Must adapt script to adjust buffer (e.g. circle9) as a function of grid cell size!
cell_size = 500
Barry = C:\Data\ArcGIS\sde_arc_connections\
Christy = C:\Users\Christina.Fandel\AppData\Roaming\ESRI\Desktop10.4\ArcCatalog\
sde_folder = ${Christy}
# eez = ${Output:root}${Output:aux}\${Output:aux}.gdb\Shoreline_EEZ

[DBConn]
enc = postgresql_dev_encd_viewer.sde
scale_usage_bands = NHSP2_0.sde

[Output]
root = ${Input:root}HH_2018\
raster = Raster
raster_classified = Raster_Class
raster_final = Raster_Final
raw = Raw
vector = Vector
vector_processed = Vector_Processed
vector_final = Vector_Final
working = Working
aux = Auxiliary
output_prj = 102008
output_prj_name = North_America_Albers_Equal_Area_Conic

[Extensions]
raster = R
vector = V
final = F
classified = C
processed = P
raw = RAW
auxiliary = AUX

[Drives]
UNC = \\ocs-s-file06.nos.noaa\HSD_DATA\NHSP_2_0\
NHSP = H:\NHSP_2_0\
HH_2018 = H:\
MAPPED = C:\Users\Christina.Fandel\Documents\ArcGIS\
HSD_DATA = ${UNC}

[AUX]
gdb = ${Output:root}${Output:aux}\${Output:aux}.gdb
fldr = ${Output:root}${Output:aux}
eez = ${gdb}\Shoreline_EEZ
eez_buffered = ${gdb}\Shoreline_EEZ_Buffer707m
eez_buffered_ras = ${gdb}\Shoreline_EEZ_Buffer707m_Raster
eez_0_ras = ${fldr}\eez_0
eez_1_ras = ${fldr}\eez_1
sandy_lt40m = ${gdb}\sandy_lt40m
sandy_lt20m_ras = ${fldr}\sandy_lt20m
sandy_lt40m_ras = ${fldr}\sandy_lt40m
catzoc_bcdu_bounds = ${gdb}\qual_bcdu
catzoc_bcdu_raster = ${fldr}\bcdu_f
grid_extents_ras =  ${Input:root}GRID\grid_ext_all
grid_extents_vec = ${Input:grid_ws}\grid_ext_all

[ActiveCaptain]
gdb = ActiveCaptain.gdb
ext = AC
out_fldr = ${Output:root}ACTIVE_CAPTAIN\
#${ext}_Circle35917

[SurveyQuality]
gdb = SurveyQuality.gdb
ext = Qual

[Reefs]
gdb = Reefs.gdb
ext = Reef

[Sanctuary]
gdb = Sanc.gdb
ext = Sanc

[Ports]
gdb = Ports.gdb
ext = Ports

[Storms]
gdb = Storms.gdb
ext = Stm
swaths = NHC_BestTrackTSWind_2004_2017
tracks = Allstorms_ibtracs_all_lines_v03r10.shp

[ISS]
gdb = ISS.gdb
ext = ISS

[Curr]
gdb = Currents.gdb
ext = curr

[Groundings]
gdb = Groundings.gdb
ext = Grnd
csv_data = Incidents2003_2016_pollution.csv
x_coords = Longitude
y_coords = Latitude

[KnownHazards]
gdb = KnownHaz.gdb
ext = HAZ

[HumanDebris]
gdb = HumanDebris.gdb
ext = HD

[RepErr]
gdb = RepErr.gdb
ext = RE

[PSS]
gdb = PSS.gdb
ext = PSS

[SAR]
gdb = SAR.gdb
ext = sar
csv_data = RAW_sar.csv
x_coords = X
y_coords = Y

[DSS]
gdb = DSS.gdb
ext = dss

[HGAP]
gdb = HGap.gdb
ext = hgap

[FSS]
gdb = FSS.gdb
ext = fss

[AIS]
gdb = AIS.gdb
ext = ais

[Depth]
gdb = depth.gdb
ext = z

[SBDARE]
gdb = sbdare.gdb
ext = sbdare

[RISK]
gdb = risk.gdb
ext = risk

[HHEALTH]
gdb = hh.gdb
ext = hh

