# CATZOC
# Data Source
#     1. HCELL CATZOC Layer, compiled from M_QUAL values stored within HCELLs on HSD Data Archive (Z:/Products/Data Archive)
#     2. MCD CATZOC Layer, compiled by Sean Legeer. (second authority) and represents data applied to the chart
#             - This layer includes three sources
#                     1. ENC
#                     2. Source (HCELL --> Source), awaiting ENC application
#                     3. 2013 Superseeded CATZOC layer that has been extensively QC'd relative to ENC Chart Histories and data available on NCEI
#                             This layer does not include F, W, or D surveys and used the following classification
#                                 Survey Type                                                           # CATZOC
#                                 Complete MBES                                                         # A1
#                                 200% SSS with concurrent MBES                                         # A1
#                                 100 % SSS with complete MBES                                          # A1
#                                 SSS (no MBES)                                                         # A2
#                                 Bathy Lidar                                                           # B
#                                 SBES Nearshore (1:40k or larger) since 1940                           # B
#                                 SBES Offshore since 1940                                              # C
#                                 1920 - 1940 surveys on known horizontal and vertical datums           # C
#                                 Pre 1940 surveys with unknown horizontal and vertical datums          # D
#                                 All surveys pre-1920                                                  # D
#             The following assumptions were made:
#                 If CATZOC = 6, then deleted from database. These areas will default to the HSD OPS CATZOC Assessment Layer
#                         Talking with Sean Legeer, CATZOC = 6 denoted (1) foreign waters for which we do not have a CATZOC value (2) Navy-only data with no CATZOC and (3) Dumping ground
#                 If CATZOC = 5 and Year = NALL, then year set to 1919.
#                         Talking with Sean Legeer, these areas are purposefully set to Year = NALL as the year of source is expected to be before 1920 (re 2013 classification). The majority of this area covers inland water ways. If HSD OPS dataset was used to replace these areas, they would likely receive a CATZOC U with no year, which is less desirable.
#                 If CATZOC = 3 and Year = NALL, then assumed to be USACE areas (following direction from Sean Legeer).
#                         CATZOC = 3/Year = NALL is merged with DREGARE and ARCHARE features from ENC Direct to extract SORDAT. Any areas where SORDAT = NULL are deleted from the database and the area will default to HSD OPS CATZOC Layer
#                 If CATZOC <> 6, 5, 3 and Year = NALL, then deleted from database. These areas will default to the HSD OPS CATZOC Assessment Layer
#
#     3. SURDEX CATZOC Assessment
#             - This layer includes two sources and is only applied in those areas where the MCD CATZOC layer has no data
#                     TECSOU/Chart Scale/Year Algorithm
#                     Note: All W and D surveys were increased by 1 (e.g. If CATZOC B, per below algorithm, and W or D survey, then CATZOC C)
#                     If TECSOU was blank, assumptions were made based on year:
#                         If year >1940 and <2000, TECSOU = 1
#                         If year >2000, TECSOU = 1, 3 (prevents assumption from being catzoc 1)
#                     OD/CC (A1)
#                     Year < 1920   (D)
#                     (TECSOU contains 3 OR TECSOU contains 1, 3) and year > 2000 AND TECSOU was not originally blank   (A2)
#                     (TECSOU contains 3 OR TECSOU contains 1, 3) and year > 2000 AND TECSOU was originally blank   (B)
#                     (TECSOU contains 2) AND (1 OR 3)  (A2)
#                     TECSOU = 2 AND Year < 2008    (C)
#                     TECSOU = 2 AND Year >= 2008   (B)
#                     (TECSOU contains 1 or 8), year > 1940, scale <= 40000     (B)
#                     (TECSOU contains 1 or 8), year > 1940, scale > 40,000     (C)
#                     (TECSOU contains 7 and 3) OR (TECSOU = 7 AND Year >= 2014)    (B)
#                     TECSOU contains 3 (B)
#                     Everything Else   (C)
# Notes:
# This script also joins the OD-classified surveys with SURDEX. The OD-classified surveys was generated by (1) reviewing DRS vs assigned coverage OR (2) reviewing PIs and assuming coverage requirements were met.
# This OD layer is used if the superseded CATZOC value is equal to 1.

# Import Modules
import arcpy
import time
import os
import collections
import arcgisscripting
from HSTB.ArcExt.NHSP import Functions
from HSTB.ArcExt.NHSP.globals import Parameters
iss = Parameters("ISS")
qual = Parameters("SurveyQuality")

# Workspace
des_sprj_name = "North_America_Albers_Equal_Area_Conic"
output_prj = 102008
cell_500 = 500
arcpy.env.outputCoordinateSystem = arcpy.SpatialReference(output_prj)
arcpy.env.geographicTransformations = output_prj

# Input Variables
out_gdb = r'H:\HH_2018\Working\SurveyQuality\CATZOC.gdb'
out_fldr = r'H:\HH_2018\Working\SurveyQuality'
grid_ws = r'H:\GRID\Grid.gdb'
enc_sde_1 = r"C:\Users\Christina.Fandel\AppData\Roaming\ESRI\Desktop10.4\ArcCatalog\postgresql_dev_encd_viewer.sde"
ub_sde_1 = r"C:\Users\Christina.Fandel\AppData\Roaming\ESRI\Desktop10.4\ArcCatalog\NHSP2_0.sde"
eez = r'H:\HH_2018\Auxiliary\Auxiliary.gdb\Shoreline_EEZ_Buffer707m'
eez_r = r'H:\HH_2018\Auxiliary\eez_0'

hcell_raw = os.path.join(out_gdb, "HCELL_CATZOC_temp1")  # 'H:\HH_2018\Raw\Raw.gdb\RAW_Qual_HCELL_CATZOC'
mcd_catzoc_raw = os.path.join(out_gdb, "MCD_CATZOC")  # 'H:\HH_2018\Raw\Raw.gdb\RAW_Qual_MCD_CATZOC'
surdex_raw = os.path.join(out_gdb, "SURDEX_01302018")  # 'H:\HH_2018\Raw\Raw.gdb\RAW_QUAL_SURDEX_01302018'
surdex_catzoc_template = r'H:\HH_2018\Working\SurveyQuality\CATZOC_ONLY_Fandel_Master.xlsx'

hcell_survey_input_field = "source"
surdex_survey_input_field = "survey"
hcell_surdex_catzoc_input_field = "HCELL_CATZOC_CATZOC"
catzoc_template_table_survey = "value"

mcd_catzoc_input_field = "CATZOC"
mcd_year_input_field = "year"
mcd_year_final_field = "year_final"
catzoc_template_sheet = "CATZOC_Master"

drgare_fn = "drgare"

features_1 = ['.drgare']
geoms_1 = ['_polygon']

od_template = r"H:\HH_2018\Working\SurveyQuality\CATZOC_OD_Fandel_Master.xlsx"
od_template_sheet = "OD_Master"
od_template_table_surveyfield = "value"
od_iss_field = "ISS"

# Output Variables
hcell_catzoc_prj = os.path.join(out_gdb, "HCELL_CATZOC_prj")  # Delete
mcd_catzoc_prj = os.path.join(out_gdb, "MCD_CATZOC_prj")  # Delete
surdex_raw_prj = os.path.join(out_gdb, "SURDEX_prj")  # Delete

mcd_catzoc_populated = os.path.join(out_gdb, "MCD_CATZOC_Populated")  # Merge Me # Delete
mcd_catzoc_unpopulated = os.path.join(out_gdb, "MCD_CATZOC_Unpopulated")  # Delete
mcd_catzoc5_populated = os.path.join(out_gdb, "MCD_CATZOC_Populated5")  # Merge me # Delete
mcd_catzoc3_populated = os.path.join(out_gdb, "MCD_CATZOC_Populated3")  # Merge Me # Delete

mcd_catzoc3_unpopulated = os.path.join(out_gdb, "MCD_CATZOC_Unpopulated3")  # Delete

drgare_year_field = "drgare_yr"
drgare_populated = os.path.join(out_gdb, "DRGARE_populated")  # Delete
drgare_populated_dissolve = os.path.join(out_gdb, "DRGARE_populated_dis")  # Delete

catzoc_template_table = os.path.join(out_gdb, "Survey_Quality_Template_Table")  # Delete
surdex_catzoc_join = os.path.join(out_gdb, "SURDEX_CATZOC_Join")  # Delete

hcell_catzoc_presupersession = os.path.join(out_gdb, "HCELL_CATZOC_presupersession")  # HCELL Presupersession Final # 'H:\HH_2018\Raw\Raw.gdb\V_Qual_HCELL_CATZOC'
mcd_catzoc_presupersession = os.path.join(out_gdb, "MCD_CATZOC_presupersession")  # MCD Presupersession Final # 'H:\HH_2018\Raw\Raw.gdb\V_Qual_MCD_CATZOC'
surdex_catzoc_presupersession = os.path.join(out_gdb, "SURDEX_CATZOC_presupersession")  # SURDEX Presupersession Final # 'H:\HH_2018\Raw\Raw.gdb\V_Qual_SURDEX_01302018'

catzoc_6 = os.path.join(out_fldr, "EEZ_CAT_6")
year_1834 = os.path.join(out_fldr, "EEZ_YR_1834")

all_presupersession_merge = os.path.join(out_gdb, "CATZOC_presupersession")  # AllPresupersession Final
all_supersession_r1 = os.path.join(out_fldr, "CATZOC_s_r1")  # Delete
all_supersession_p1 = os.path.join(out_gdb, "CATZOC_s_p1")  # Delete

catzoc_final_t = os.path.join(out_fldr, "CATZOC_Ft")  # Delete
year_final_t = os.path.join(out_fldr, "S_YR_Ft")  # Delete

catzoc_raster = os.path.join(out_fldr, "r_qual")
year_raster = os.path.join(out_fldr, "r_qual_yr")

year_final_p = os.path.join(out_gdb, "S_YR_poly_F")
catzoc_final_p = os.path.join(out_gdb, "CATZOC_poly_F")

catzoc_RC = os.path.join(out_fldr, "CATZOC_RC")

catzoc_final = os.path.join(out_fldr, "CATZOC_F")  # 'H:\HH_2018\Raster_Final\RF_Qual'

age_final = os.path.join(out_fldr, "S_Age_F")
catzoc_bcdu_final_p = os.path.join(out_gdb, "BCDU_poly_F")
catzoc_bcdu_final = os.path.join(out_fldr, "BCDU_F")

od_template_table = os.path.join(out_gdb, "OD_Template_Table")

# Define Variables
hcell_no6_query = hcell_surdex_catzoc_input_field + " <> 6"
mcd_nonull_query = "SUREND IS NOT NULL AND SUREND <> ' ' AND SUREND <> '<Null>'"
mcd_unpopulated_catzoc5_query = mcd_catzoc_input_field + " = '5'"
mcd_catzoc3_query = mcd_catzoc_input_field + " = '3'"
drgare_nonull_query = "SORDAT IS NOT NULL AND SORDAT <> ' ' AND SORDAT <> '<Null>'"
surdex_query = "Survey_Quality_Template_Table_CATZOC_Final IS NOT NULL AND (SURDEX_01302018_chart <> 'N' OR (SURDEX_01302018_chart IS NULL AND SURDEX_01302018_status <> 'P'))"
priority_fieldname = "catzoc_year_priority_field"

final_superseded_catzoc_year_field_str = "gridcode_str"
final_superseded_catzoc_year_field_str_calc = "!gridcode!"
temp_superseded_catzoc_field = "CATZOC_temp_Super_Final"
final_superseded_catzoc_field = "CATZOC_Superseded_Final"

temp_superseded_catzoc_field_calc = "!%s![0]!" % (final_superseded_catzoc_year_field_str)
final_superseded_catzoc_field_calc = "6-!%s!" % (temp_superseded_catzoc_field)
final_superseded_year_field = "Year_Superseded_Final"
final_superseded_year_field_calc = "!%s![len(!%s!)-4:len(!%s!)]" % (final_superseded_catzoc_year_field_str, final_superseded_catzoc_year_field_str, final_superseded_catzoc_year_field_str)

final_survey_age_field = "survey_age"
final_survey_age_calc = "2018-!gridcode!"
final_catzoc_bcdu_calc = "gridcode>2"

mcd_year_final_field_calc = "!SUREND![0:4]"
drgare_dbl_year_calc = "!SORDAT![0:4]"
mcd_catzoc3_year_calc = "!" + drgare_year_field + "!"

surdex_od_join = os.path.join(out_gdb, "od_surdex_join")
surdex_od_chart_query = "(SURDEX_01302018_chart <> 'N' OR (SURDEX_01302018_chart IS NULL AND SURDEX_01302018_status <> 'P'))"
surdex_od_join_filtered = os.path.join(out_gdb, "od_surdex_join_filtered")
qual_od = os.path.join(out_fldr, "R_Qual_od")

# RAW DATA
# Check Spatial Reference of CATZOC layers
hcell_prj = Functions.check_spatial_reference(out_gdb, os.path.split(hcell_raw)[1], os.path.split(hcell_catzoc_prj)[1] + "_prj", des_sprj_name, output_prj)
mcd_prj = Functions.check_spatial_reference(out_gdb, os.path.split(mcd_catzoc_raw)[1], os.path.split(mcd_catzoc_prj)[1] + "_prj", des_sprj_name, output_prj)
surdex_prj = Functions.check_spatial_reference(out_gdb, os.path.split(surdex_raw)[1], os.path.split(surdex_raw_prj)[1] + "_prj", des_sprj_name, output_prj)

# HCELL Data
# For each input dataset (e.g. HCell, MCD, and SURDEX), confirm CATZOC and Year values for each survey, then generate superseded CATZOC/Year field based on priority of input dataset
# Join HCELL Dataset with SURDEX (to retrieve year)
try:
    hcell_layer = "hcell_lyr"
    arcpy.MakeFeatureLayer_management(hcell_prj, hcell_layer)
    arcpy.AddJoin_management(hcell_layer, hcell_survey_input_field, surdex_prj, surdex_survey_input_field, "KEEP_ALL")
    arcpy.FeatureClassToFeatureClass_conversion(hcell_layer, os.path.split(hcell_prj)[0], os.path.split(hcell_prj)[1])
except arcgisscripting.RuntimeError:
    print("Unable to add join, verify New Map is opened in ArcPro. e.g. Insert --> New Map.")

# Remove HCELL CATZOC Values = 6
arcpy.Select_analysis(hcell_prj, hcell_catzoc_presupersession, hcell_no6_query)
# NOTE: Should consider filtering to only include those surveys applied to chart. Note, for 2018 run of the model, spot investigated 9 surveys that met this requirements. All that met "not charted" were consistent with MCD layer, or were in error as described in the database, referencing notes from Survey Tracker.


######
# At this point, must feed into supersession check to
# 1. Check to see that catzoc and year fields are double/integer, if not, add double/integer field for these two variables
# 2. Based on priority, calculate superseded field in vector space

# MCD Data
#################################################################

# Extract the following
# (1) CATZOC is populated and SUREND is populated
mcd_temp_layer = "mcd_temp_layer"
arcpy.MakeFeatureLayer_management(mcd_prj, mcd_temp_layer)
arcpy.SelectLayerByAttribute_management(mcd_temp_layer, "NEW_SELECTION", mcd_nonull_query)
arcpy.FeatureClassToFeatureClass_conversion(mcd_temp_layer, os.path.split(mcd_catzoc_populated)[0], os.path.split(mcd_catzoc_populated)[1])
arcpy.SelectLayerByAttribute_management(mcd_temp_layer, "CLEAR_SELECTION")

# (2) CATZOC is not populated or SUREND is not populated
arcpy.SelectLayerByAttribute_management(mcd_temp_layer, "NEW_SELECTION", mcd_nonull_query, "INVERT")
arcpy.FeatureClassToFeatureClass_conversion(mcd_temp_layer, os.path.split(mcd_catzoc_unpopulated)[0], os.path.split(mcd_catzoc_unpopulated)[1])
arcpy.SelectLayerByAttribute_management(mcd_temp_layer, "CLEAR_SELECTION")

# CATZOC-populated MCD Layer: Add "Year" field (dbl) to MCD layer and populate with SUREND-populated file, with SUREND (str)
arcpy.AddField_management(mcd_prj, mcd_year_input_field, "double")
arcpy.CalculateField_management(mcd_catzoc_populated, mcd_year_final_field, mcd_year_final_field_calc, "PYTHON3")

# CATZOC - unpopulated MCD Layer: Extract, from unpopulated SUREND layer, CATZOC = 5 and set Year = 1919
mcd_unpop_temp_layer = "mcd_unpop_temp_lyr"
arcpy.MakeFeatureLayer_management(mcd_catzoc_unpopulated, mcd_unpop_temp_layer)
arcpy.SelectLayerByAttribute_management(mcd_unpop_temp_layer, "NEW_SELECTION", mcd_unpopulated_catzoc5_query)
arcpy.CalculateField_management(mcd_unpop_temp_layer, mcd_year_final_field, 1919)
arcpy.FeatureClassToFeatureClass_conversion(mcd_unpop_temp_layer, os.path.split(mcd_catzoc5_populated)[0], os.path.split(mcd_catzoc5_populated)[1])
arcpy.SelectLayerByAttribute_management(mcd_unpop_temp_layer, "CLEAR_SELECTION")

# Extract, from unpopulated SUREND layer, CATZOC = 3 - Spatially merge with DREGARE for year (SURDAT). All areas with out a corresponding DREGARE will be discarded and HSD OPS layer will be used to predict CATZOC.
arcpy.Select_analysis(mcd_catzoc_unpopulated, mcd_catzoc3_unpopulated, mcd_catzoc3_query)
drgare = Functions.extract_enc_data(enc_sde_1, ub_sde_1, out_gdb, features_1, geoms_1, drgare_fn, output_prj)
# Add Year Field to DRGARE Data, Remove NULL SORDAT Fields, Populate Year Field with SORDAT
arcpy.AddField_management(drgare, drgare_year_field, "double")
arcpy.Select_analysis(drgare, drgare_populated, drgare_nonull_query)
arcpy.CalculateField_management(drgare_populated, drgare_year_field, drgare_dbl_year_calc, "PYTHON3")
arcpy.Dissolve_management(drgare_populated, drgare_populated_dissolve, drgare_year_field)
# Spatially Join MCD CATZOC 3 Layer and DRGARE - must split up by grid area, otherwise ESRI crashes
# Note: this was not working in Pro, so was run in ArcMap (where it was working just fine)
mcd_cat3_unpop_list = []
mcd_cat3_pop_list = []
for igrid in range(1, 14):
    t_start = time.time()
    grid_name = "Model_Extents_%02d" % igrid
    grid_path = os.path.join(grid_ws, grid_name)
    mcd_catzoc3_unpopulated_grid = "mcd_catzoc3_unpop_%02d" % igrid
    mcd_catzoc3_unpopulated_grid_path = os.path.join(out_gdb, mcd_catzoc3_unpopulated_grid)
    mcd_catzoc3_populated_grid = "mcd_catzoc3_pop_%02d" % igrid
    mcd_catzoc3_populated_grid_path = os.path.join(out_gdb, mcd_catzoc3_populated_grid)

    arcpy.Clip_analysis(mcd_catzoc3_unpopulated, grid_path, mcd_catzoc3_unpopulated_grid_path)
    arcpy.SpatialJoin_analysis(mcd_catzoc3_unpopulated_grid_path, drgare_populated_dissolve, mcd_catzoc3_populated_grid_path, "JOIN_ONE_TO_ONE", "KEEP_COMMON", "", "INTERSECT", "", "")

    mcd_cat3_unpop_list.append(mcd_catzoc3_unpopulated_grid_path)
    mcd_cat3_pop_list.append(mcd_catzoc3_populated_grid_path)

# Merge all Catzoc = 3 populated files
arcpy.Merge_management(mcd_cat3_pop_list, mcd_catzoc3_populated)

# Copy DRGARE Year to CATZOC Year Field
arcpy.CalculateField_management(mcd_catzoc3_populated, mcd_year_input_field, mcd_catzoc3_year_calc, "PYTHON3")

# Merge CATZOC3_Populated, CATZOC5_Populated, and MCD_Populated
arcpy.Merge_management([mcd_catzoc3_populated, mcd_catzoc5_populated, mcd_catzoc_populated], mcd_catzoc_presupersession)

# SURDEX DATA
#################################################################

# Convert CATZOC Template to Table
arcpy.ExcelToTable_conversion(surdex_catzoc_template, catzoc_template_table, catzoc_template_sheet)

# Join SURDEX layer with CATZOC Template Excel Spreadsheet to retrieve approximated CATZOC value for each survey within SURDEX database
try:
    surdex_layer = "surdex_lyr"
    arcpy.MakeFeatureLayer_management(surdex_prj, surdex_layer)
    arcpy.AddJoin_management(surdex_layer, surdex_survey_input_field, catzoc_template_table, catzoc_template_table_survey, "KEEP_ALL")
    arcpy.FeatureClassToFeatureClass_conversion(surdex_layer, os.path.split(surdex_catzoc_join)[0], os.path.split(surdex_catzoc_join)[1])
except arcgisscripting.RuntimeError:
    print("Unable to add join, verify New Map is opened in ArcPro. e.g. Insert --> New Map.")

# Select CATZOC = NULL values and change to CATZOC = 6. Remove surveys for which data was not applied to the chart.
surdex_temp1_layer = "surdex_temp1_lyr"  # Need New
surdex_catzoc_temp1 = os.path.join(out_gdb, "surdex_catzoc_temp1")
arcpy.MakeFeatureLayer_management(surdex_catzoc_temp1, surdex_temp1_layer)
arcpy.SelectLayerByAttribute_management(surdex_temp1_layer, "NEW_SELECTION", surdex_query)
arcpy.CalculateField_management(surdex_temp1_layer, "Survey_Quality_Template_Table_CATZOC_Final", 6)
arcpy.SelectLayerByAttribute_management(surdex_temp1_layer, "CLEAR_SELECTION")
arcpy.FeatureClassToFeatureClass_conversion(surdex_temp1_layer, os.path.split(surdex_catzoc_presupersession)[0], os.path.split(surdex_catzoc_presupersession)[1])

# Raster Data
# Create underlying CATZOC 6/YEAR 1834 layer based on EEZ Bounds
#arcpy.AddField_management(eez, priority_fieldname, "double")
#arcpy.CalculateField_management(eez, priority_fieldname, 11834)
eez_catzoc_field = "CATZOC"
eez_year_field = "YEAR"
arcpy.AddField_management(eez, "CATZOC", "double")
arcpy.CalculateField_management(eez, eez_catzoc_field, 6)
arcpy.PolygonToRaster_conversion(eez, eez_catzoc_field, catzoc_6, "MAXIMUM_COMBINED_AREA", eez_catzoc_field, cell_500)

arcpy.AddField_management(eez, eez_year_field, "double")
arcpy.CalculateField_management(eez, eez_year_field, 1834)
arcpy.PolygonToRaster_conversion(eez, eez_year_field, year_1834, "MAXIMUM_COMBINED_AREA", eez_year_field, cell_500)

# HCELL, MCD, SURDEX Data
presupersession_files = [hcell_catzoc_presupersession, mcd_catzoc_presupersession, surdex_catzoc_presupersession]

# Generate HCell, MCD, and SURDEX File Bounds
for file in presupersession_files:
    Functions.generate_polygon_bounds(file, out_gdb)

# Calculate Superseded CATZOC and Year Field based on priority of layer (Hcell = 1, MCD = 2, and SURDEX = 3)
Functions.calc_superseded_catzoc_year(hcell_catzoc_presupersession, "CATZOC_Final", "Year_Final", out_gdb, out_fldr, cell_500, priority_fieldname, 1, 3)
Functions.calc_superseded_catzoc_year(mcd_catzoc_presupersession, "CATZOC_Final", "Year", out_gdb, out_fldr, cell_500, priority_fieldname, 2, 3)
Functions.calc_superseded_catzoc_year(surdex_catzoc_presupersession, "Survey_Quality_Template_Table_CATZOC_Final", "SURDEX_01302018_year", out_gdb, out_fldr, cell_500, priority_fieldname, 3, 3)

# Merge presuperseded files based on superseded catzoc/year field
# presupersession_files.append(eez)
arcpy.Merge_management(presupersession_files, all_presupersession_merge)

# Convert merged polygon to raster based on superseded field, then back to polygon to extract superseded CATZOC and Year Values
arcpy.PolygonToRaster_conversion(all_presupersession_merge, priority_fieldname, all_supersession_r1, "MAXIMUM_COMBINED_AREA", priority_fieldname, cell_500)
arcpy.RasterToPolygon_conversion(all_supersession_r1, all_supersession_p1, "NO_SIMPLIFY", "value")

# Extract Superseded CATZOC and Year Field
arcpy.AddField_management(all_supersession_p1, final_superseded_catzoc_year_field_str, "TEXT", "", "", 100)
arcpy.CalculateField_management(all_supersession_p1, final_superseded_catzoc_year_field_str, final_superseded_catzoc_year_field_str_calc)

arcpy.AddField_management(all_supersession_p1, final_superseded_year_field, "double")
arcpy.CalculateField_management(all_supersession_p1, final_superseded_year_field, final_superseded_year_field_calc)

temp_superseded_catzoc_field = "CATZOC_temp_Super_Final"
arcpy.AddField_management(all_supersession_p1, temp_superseded_catzoc_field, "double")
arcpy.CalculateField_management(all_supersession_p1, temp_superseded_catzoc_field, temp_superseded_catzoc_field_calc)
arcpy.AddField_management(all_supersession_p1, final_superseded_catzoc_field, "double")
arcpy.CalculateField_management(all_supersession_p1, final_superseded_catzoc_field, final_superseded_catzoc_field_calc)

# Create Superseded CATZOC and Year Rasters, then merge with EEZ file
arcpy.PolygonToRaster_conversion(all_supersession_p1, final_superseded_catzoc_field, catzoc_final_t, "MAXIMUM_COMBINED_AREA", final_superseded_catzoc_field, cell_500)
arcpy.PolygonToRaster_conversion(all_supersession_p1, final_superseded_year_field, year_final_t, "MAXIMUM_COMBINED_AREA", final_superseded_year_field, cell_500)

arcpy.MosaicToNewRaster_management([catzoc_final_t, catzoc_6], out_fldr, os.path.split(catzoc_raster)[1], output_prj, "32_BIT_SIGNED", str(cell_500), "1", "MINIMUM", "FIRST")
arcpy.MosaicToNewRaster_management([year_final_t, year_1834], out_fldr, os.path.split(year_raster)[1], output_prj, "32_BIT_SIGNED", str(cell_500), "1", "MAXIMUM", "FIRST")

# Create Object Detection Layer
# Convert CATZOC Template to Table
arcpy.ExcelToTable_conversion(od_template, od_template_table, od_template_sheet)

# Join SURDEX layer with CATZOC Template Excel Spreadsheet to retrieve approximated CATZOC value for each survey within SURDEX database
try:
    surdex_od_layer = "surdex_od_lyr"
    arcpy.MakeFeatureLayer_management(surdex_prj, surdex_od_layer)
    arcpy.AddJoin_management(surdex_od_layer, surdex_survey_input_field, od_template_table, od_template_table_surveyfield, "KEEP_COMMON")
    arcpy.FeatureClassToFeatureClass_conversion(surdex_od_layer, os.path.split(surdex_od_join)[0], os.path.split(surdex_od_join)[1])
except arcgisscripting.RuntimeError:
    print("Unable to add join, verify New Map is opened in ArcPro. e.g. Insert --> New Map.")

# Remove any surveys that were not applied to the chart
surdex_query = "Survey_Quality_Template_Table_CATZOC_Final IS NOT NULL AND (SURDEX_01302018_chart <> 'N' OR (SURDEX_01302018_chart IS NULL AND SURDEX_01302018_status <> 'P'))"

# Select CATZOC = NULL values and change to CATZOC = 6. Remove surveys for which data was not applied to the chart.
od_temp_lyr = "od_temp1_lyr"  # Need New
# od_temp1 = os.path.join(out_gdb, "od_temp1")
arcpy.MakeFeatureLayer_management(surdex_od_join, od_temp_lyr)
arcpy.SelectLayerByAttribute_management(od_temp_lyr, "NEW_SELECTION", surdex_od_chart_query)
arcpy.SelectLayerByAttribute_management(od_temp_lyr, "CLEAR_SELECTION")
arcpy.FeatureClassToFeatureClass_conversion(od_temp_lyr, os.path.split(surdex_od_join_filtered)[0], os.path.split(surdex_od_join_filtered)[1])

# Add ISS field
# CATZOC-populated MCD Layer: Add "Year" field (dbl) to MCD layer and populate with SUREND-populated file, with SUREND (str)
arcpy.AddField_management(surdex_od_join_filtered, od_iss_field, "double")
arcpy.CalculateField_management(surdex_od_join_filtered, od_iss_field, 110, "PYTHON3")

arcpy.PolygonToRaster_conversion(surdex_od_join_filtered, od_iss_field, qual_od, "MAXIMUM_COMBINED_AREA", od_iss_field, cell_500)

'''# Create Survey Age Raster
arcpy.RasterToPolygon_conversion(year_raster, year_final_p, "NO_SIMPLIFY", "value")
arcpy.AddField_management(year_final_p, final_survey_age_field, "double")
arcpy.CalculateField_management(year_final_p,final_survey_age_field,final_survey_age_calc)
arcpy.PolygonToRaster_conversion(year_final_p, final_survey_age_field, age_final, "MAXIMUM_COMBINED_AREA", final_survey_age_field, cell_500)

# Create Superseded CATZOC BCDU Raster
arcpy.RasterToPolygon_conversion(catzoc_raster, catzoc_final_p, "NO_SIMPLIFY", "value")
arcpy.Select_analysis(catzoc_final_p, catzoc_bcdu_final_p, final_catzoc_bcdu_calc)
arcpy.PolygonToRaster_conversion(catzoc_bcdu_final_p, "gridcode", catzoc_bcdu_final, "MAXIMUM_COMBINED_AREA", "gridcode", cell_500)
Functions.generate_polygon_bounds(catzoc_bcdu_final_p, out_gdb)

# Reclassify CATZOC Raster using the following classification
# CATZOC
# A1         # 1
# A2         # 1
# B          # 3
# C          # 4
# D          # 5
# U          # 5

r = arcpy.sa.Reclassify(catzoc_raster, "VALUE", "1 1;2 1;3 3;4 4;5 5;6 5", "DATA")
r.save(catzoc_RC)

# Clip Final CATZOC_RC to EEZ Bounds
e = arcpy.sa.ExtractByMask(catzoc_RC, eez_r)
e.save(catzoc_final)'''

# Delete Unnecessary Files
del_fns = [od_template_table, hcell_catzoc_prj, mcd_catzoc_prj, surdex_raw_prj, mcd_catzoc_populated, mcd_catzoc_unpopulated, mcd_catzoc5_populated, mcd_catzoc3_populated, mcd_catzoc3_unpopulated, drgare_populated, drgare_populated_dissolve, catzoc_template_table, surdex_catzoc_join, all_supersession_r1, all_supersession_p1, catzoc_final_t, year_final_t] + mcd_cat3_unpop_list + mcd_cat3_pop_list

for fn in del_fns:  # enumerate retrieves index number
    print(("Deleting: %s") % (str(fn)))
    arcpy.Delete_mangagement(str(fn))

# Polygon to Raster (under the hood)
# In short, if overlapping polygons, tool will supersede using the value of the polygon that takes up the most space within the cell.
# If overlapping polygons take up the same amount of space, it will take the higher value of the priority field. As such CATZOC/YEAR were
# combined such that (10000*(6-CATZOC))+Year to achieve the maximum combination of Year and CATZOC

# MAXIMUM_COMBINED_AREA METHOD
# For this description, the combined feature is considered to be a single feature with the FID equal to the lowest of the
# combined features and the priority equal to the highest of the combined features.

# If no priority is specified, and
    # Only one feature overlaps the cell, it must overlap by at least 50% to be selected.
    # Only one feature has the largest area, then it is selected.
    # More than one feature has the same size area, then the one with the lowest FID is selected.
# If priority is specified, and;
    # The feature in question overlaps the cell by less than 50%, and
    # The priority is greater than zero, then it is considered.
    # The priority is equal to zero, then the feature is not considered.
    # Only one feature has the largest area, then it is selected.
    # More than one feature has the same largest area, and
    # Their priorities are different, then the one with the highest priority is selected.
    # Their priorities are the same, then the one with the smallest FID is selected.
    # The feature boundary coincides with a cell boundary, then the boundary rules apply. '''
